// dishes.js

const meals = [
    // Супы
    {
      keyword: "kyrica",
      name: "Куриный суп",
      price: 330,
      category: "soup",
      kind: "meat",
      count: "350 мл",
      image: "/images/menu/soups/chikcen_soup.jpg",
    },
    {
      keyword: "grib",
      name: "Грибной суп",
      price: 185,
      category: "soup",
      kind: "veg",
      count: "330 мл",
      image: "/images/menu/soups/mushroom_soup.jpg",
    },
    {
      keyword: "gazpacho",
      name: "Гаспачо",
      price: 195,
      category: "soup",
      kind: "veg",
      count: "350 мл",
      image: "/images/menu/soups/gazpacho.jpg",
    },
    {
      keyword: "norwegian_soup",
      name: "Норвежский суп",
      price: 270,
      category: "soup",
      kind: "meat",
      count: "330 мл",
      image: "/images/menu/soups/norwegian_soup.jpg",
    },
    {
      keyword: "ramen",
      name: "Рамен",
      price: 375,
      category: "soup",
      kind: "meat",
      count: "425 мл",
      image: "/images/menu/soups/ramen.jpg",
    },
    {
      keyword: "tomYam",
      name: "Том ям с креветками",
      price: 650,
      category: "soup",
      kind: "fish",
      count: "500 мл",
      image: "/images/menu/soups/tom_yam.jpg",
    },
  
    // Главное блюдо
    {
      keyword: "potato_mushrooms",
      name: "Жареная картошка с грибами",
      price: 150,
      category: "main",
      kind: "veg",
      count: "250 гр",
      image: "/images/menu/main_course/friedpotatoeswithmushrooms1.jpg",
    },
    {
      keyword: "lasagna",
      name: "Лазанья",
      price: 385,
      category: "main",
      kind: "veg",
      count: "310 гр",
      image: "/images/menu/main_course/lasagna.jpg",
    },
    {
      keyword: "kotlet_chicken",
      name: "Котлеты из курицы с картофельным пюре",
      price: 225,
      category: "main",
      kind: "meat",
      count: "280 гр",
      image: "/images/menu/main_course/chickencutletsandmashedpotatoes.jpg",
    },
    {
      keyword: "kotlet_fish",
      name: "Рыбные котлеты с рисом и спаржей",
      price: 330,
      category: "main",
      kind: "fish",
      count: "250 гр",
      image: "/images/menu/main_course/Fish_cutlet_with_rice_and_asparagus.jpg",
    },
    {
      keyword: "pizza",
      name: "Пицца Маргарита",
      price: 450,
      category: "main",
      kind: "meat",
      count: "470 гр",
      image: "/images/menu/main_course/Pizza_Margarita.jpg",
    },
    {
      keyword: "pasta",
      name: "Паста с креветками",
      price: 340,
      category: "main",
      kind: "fish",
      count: "280 гр",
      image: "/images/menu/main_course/Pasta_with_shrimp.jpg",
    },
  
    // Салаты и стартеры
    {
      keyword: "saladwithovos",
      name: "Корейский салат с овощами и яйцом",
      price: 330,
      category: "salad",
      count: "250 г",
      image: "/images/menu/salad/Korean_salad_with_vegetables_and_egg.jpg",
      kind: "veg",
    },
    {
      keyword: "cesar",
      name: "Цезарь с цыпленком",
      price: 370,
      category: "salad",
      count: "220 г",
      image: "/images/menu/salad/Caesar_with_chicken.jpg",
      kind: "meat",
    },
    {
      keyword: "caprese",
      name: "Капрезе с моцареллой",
      price: 350,
      category: "salad",
      count: "235 г",
      image: "/images/menu/salad/caprese_with_mozzarella.jpg",
      kind: "veg",
    },
    {
      keyword: "saladtuna",
      name: "Салат с тунцом",
      price: 490,
      category: "salad",
      count: "250 г",
      image: "/images/menu/salad/tuna_salad.jpg",
      kind: "fish",
    },
    {
      keyword: "free_cesar",
      name: "Картофель фри с соусом Цезарь",
      price: 280,
      category: "salad",
      kind: "veg",
      count: "235г",
      image: "/images/menu/salad/French_fries_with_ketchup_sauce.jpg",
    },
    {
      keyword: "free_ketch",
      name: "Картофель фри с кетчупом",
      price: 260,
      category: "salad",
      kind: "veg",
      count: "235г",
      image: "/images/menu/salad/French_fries_with_ketchup_sauce.jpg",
    },
  
    // Десерты
    {
      keyword: "pahlava",
      name: "Пахлава",
      price: 220,
      category: "dessert",
      count: "300 г",
      kind: "medium",
      image: "/images/menu/desert/baklava.jpg",
    },
    {
      keyword: "cheescake",
      name: "Чизкейк",
      price: 240,
      category: "dessert",
      count: "125 г",
      kind: "small",
      image: "/images/menu/desert/cheesecake.jpg",
    },
    {
      keyword: "chocolate_cheescake",
      name: "Шоколадный чизкейк",
      price: 260,
      category: "dessert",
      count: "125 г",
      kind: "small",
      image: "/images/menu/desert/chocolate_cheesecake.jpg",
    },
    {
      keyword: "shoko_cake",
      name: "Шоколадный торт",
      price: 270,
      category: "dessert",
      kind: "medium",
      count: "140 г",
      image: "/images/menu/desert/chocolate_cake.jpg",
    },
    {
      keyword: "3donats",
      name: "Пончики (3 штуки)",
      price: 410,
      category: "dessert",
      count: "350 г",
      kind: "medium",
      image: "/images/menu/desert/donats3.jpg",
    },
    {
      keyword: "7donats",
      name: "Пончики (7 штук)",
      price: 650,
      category: "dessert",
      kind: "large",
      count: "700г",
      image: "/images/menu/desert/donats7.jpg",
    },
  
    // Напитки
    {
      keyword: "apelsin",
      name: "Апельсиновый сок",
      price: 120,
      count: "300 мл",
      image: "/images/menu/beverages/applejuice.jpg",
      category: "drink",
      kind: "cold",
    },
    {
      keyword: "apple",
      name: "Яблочный сок",
      price: 110,
      count: "300 мл",
      image: "/images/menu/beverages/applejuice.jpg",
      category: "drink",
      kind: "cold",
    },
    {
      keyword: "carrot",
      name: "Морковный сок",
      price: 110,
      count: "300 мл",
      image: "/images/menu/beverages/carrotjuice.jpg",
      category: "drink",
      kind: "cold",
    },
    {
      keyword: "capuccino",
      name: "Капучино",
      price: 180,
      count: "300 мл",
      image: "/images/menu/beverages/cappuccino.jpg",
      category: "drink",
      kind: "hot",
    },
    {
      keyword: "greentea",
      name: "Зеленый чай",
      price: 100,
      count: "300 мл",
      image: "/images/menu/beverages/Green_tea.jpg",
      category: "drink",
      kind: "hot",
    },
    {
      keyword: "blacktea",
      name: "Черный чай",
      price: 90,
      category: "drink",
      kind: "hot",
      count: "300 мл",
      image: "/images/menu/beverages/Blacktea.jpg",
    },
  ];